//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        public Sensor()
        {
            this.SensorData = new HashSet<SensorData>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Address { get; set; }
        public Nullable<int> CoordinatorID { get; set; }
        public byte Type { get; set; }
    
        public virtual Coordinator Coordinator { get; set; }
        public virtual ICollection<SensorData> SensorData { get; set; }
    }
}
